// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: connect_response.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientSlot int32   `protobuf:"varint,1,opt,name=ClientSlot,proto3" json:"ClientSlot,omitempty"`
	Px         float64 `protobuf:"fixed64,2,opt,name=px,proto3" json:"px,omitempty"`
	Py         float64 `protobuf:"fixed64,3,opt,name=py,proto3" json:"py,omitempty"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_connect_response_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectResponse) GetClientSlot() int32 {
	if x != nil {
		return x.ClientSlot
	}
	return 0
}

func (x *ConnectResponse) GetPx() float64 {
	if x != nil {
		return x.Px
	}
	return 0
}

func (x *ConnectResponse) GetPy() float64 {
	if x != nil {
		return x.Py
	}
	return 0
}

var File_connect_response_proto protoreflect.FileDescriptor

var file_connect_response_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x51, 0x0a, 0x0f,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x70, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x70, 0x78, 0x12,
	0x0e, 0x0a, 0x02, 0x70, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x70, 0x79, 0x42,
	0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69,
	0x73, 0x75, 0x6e, 0x6a, 0x69, 0x2f, 0x65, 0x62, 0x69, 0x74, 0x65, 0x6e, 0x2d, 0x70, 0x6f, 0x63,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connect_response_proto_rawDescOnce sync.Once
	file_connect_response_proto_rawDescData = file_connect_response_proto_rawDesc
)

func file_connect_response_proto_rawDescGZIP() []byte {
	file_connect_response_proto_rawDescOnce.Do(func() {
		file_connect_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_connect_response_proto_rawDescData)
	})
	return file_connect_response_proto_rawDescData
}

var file_connect_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connect_response_proto_goTypes = []interface{}{
	(*ConnectResponse)(nil), // 0: pb.ConnectResponse
}
var file_connect_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_connect_response_proto_init() }
func file_connect_response_proto_init() {
	if File_connect_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connect_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connect_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connect_response_proto_goTypes,
		DependencyIndexes: file_connect_response_proto_depIdxs,
		MessageInfos:      file_connect_response_proto_msgTypes,
	}.Build()
	File_connect_response_proto = out.File
	file_connect_response_proto_rawDesc = nil
	file_connect_response_proto_goTypes = nil
	file_connect_response_proto_depIdxs = nil
}
