// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: update_entity.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UpdateEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Fx    int32   `protobuf:"varint,2,opt,name=Fx,proto3" json:"Fx,omitempty"`
	Fy    int32   `protobuf:"varint,3,opt,name=Fy,proto3" json:"Fy,omitempty"`
	Vx    int32   `protobuf:"varint,4,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy    int32   `protobuf:"varint,5,opt,name=vy,proto3" json:"vy,omitempty"`
	Px    float64 `protobuf:"fixed64,6,opt,name=Px,proto3" json:"Px,omitempty"`
	Py    float64 `protobuf:"fixed64,7,opt,name=Py,proto3" json:"Py,omitempty"`
	Speed int32   `protobuf:"varint,8,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *UpdateEntity) Reset() {
	*x = UpdateEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntity) ProtoMessage() {}

func (x *UpdateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_update_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntity.ProtoReflect.Descriptor instead.
func (*UpdateEntity) Descriptor() ([]byte, []int) {
	return file_update_entity_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateEntity) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UpdateEntity) GetFx() int32 {
	if x != nil {
		return x.Fx
	}
	return 0
}

func (x *UpdateEntity) GetFy() int32 {
	if x != nil {
		return x.Fy
	}
	return 0
}

func (x *UpdateEntity) GetVx() int32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *UpdateEntity) GetVy() int32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *UpdateEntity) GetPx() float64 {
	if x != nil {
		return x.Px
	}
	return 0
}

func (x *UpdateEntity) GetPy() float64 {
	if x != nil {
		return x.Py
	}
	return 0
}

func (x *UpdateEntity) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File_update_entity_proto protoreflect.FileDescriptor

var file_update_entity_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9a, 0x01, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x0e, 0x0a, 0x02, 0x46, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x46, 0x78,
	0x12, 0x0e, 0x0a, 0x02, 0x46, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x46, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x76, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x76, 0x78,
	0x12, 0x0e, 0x0a, 0x02, 0x76, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x76, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x50, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x50, 0x78,
	0x12, 0x0e, 0x0a, 0x02, 0x50, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x50, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x73, 0x75, 0x6e, 0x6a, 0x69, 0x2f, 0x65, 0x62, 0x69,
	0x74, 0x65, 0x6e, 0x2d, 0x70, 0x6f, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_update_entity_proto_rawDescOnce sync.Once
	file_update_entity_proto_rawDescData = file_update_entity_proto_rawDesc
)

func file_update_entity_proto_rawDescGZIP() []byte {
	file_update_entity_proto_rawDescOnce.Do(func() {
		file_update_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_update_entity_proto_rawDescData)
	})
	return file_update_entity_proto_rawDescData
}

var file_update_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_update_entity_proto_goTypes = []interface{}{
	(*UpdateEntity)(nil), // 0: pb.UpdateEntity
}
var file_update_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_update_entity_proto_init() }
func file_update_entity_proto_init() {
	if File_update_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_update_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_update_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_update_entity_proto_goTypes,
		DependencyIndexes: file_update_entity_proto_depIdxs,
		MessageInfos:      file_update_entity_proto_msgTypes,
	}.Build()
	File_update_entity_proto = out.File
	file_update_entity_proto_rawDesc = nil
	file_update_entity_proto_goTypes = nil
	file_update_entity_proto_depIdxs = nil
}
